In [1]:
%matplotlib inline

Autograd:Automatic Differntiation

In [2]:
import torch

Create a tensor and set requires_grad=True to track computation with it

In [3]:
x=torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y=x+1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [5]:
z  = y * y * 3
out=z.mean()

print(z,out)

tensor([[12., 12.],
        [12., 12.]], grad_fn=<MulBackward0>) tensor(12., grad_fn=<MeanBackward0>)


out contains a single scalar out.backward() is equivalent to out.backward(torch.tensor(1,)).

In [6]:
out.backward()

In [7]:
x.grad

tensor([[3., 3.],
        [3., 3.]])

In [8]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ -17.0606, -738.5286,  844.8920], grad_fn=<MulBackward0>)


In [9]:
X=torch.tensor([1.],requires_grad=True)

In [10]:
output=X + X*2

In [11]:
desired_output=10

In [12]:
loss =(desired_output - output)

In [13]:
loss.backward()

In [14]:
X.grad = torch.ones_like(X)
X=X-.1*X.grad
X

tensor([0.9000], grad_fn=<SubBackward0>)

In [15]:
loss =(desired_output - output)
X.grad = torch.ones_like(X)
X=X-.1*X.grad
X

tensor([0.8000], grad_fn=<SubBackward0>)

NEW