In [1]:
%matplotlib inline

**PyTorch**

**What is PyToch**

It's a Python-based scientific computing package targeted at two sets of auddiences




=>A replacement for NumPy to use the power of GPUs

=>A deep Learning research platform that provides maximum flexibility and speed




In [2]:
import torch

**NOTE**


```
An unintialized matrix is declared,but does not contain definite known values it is used.
When an unintialized matrix is created,whatever values were in the allocated memory at the time will apear as the initial values.



```



 construct a 5x3 matrix, unintialized

In [3]:
 x=torch.empty(5,3)

 print(x)

tensor([[4.1254e-41, 5.1837e-39, 3.0545e-27],
        [2.5353e+30, 1.1491e-43, 3.0293e-41],
        [2.2449e-39, 3.1278e-24, 2.5353e+30],
        [3.5032e-44, 9.4868e-42, 8.6096e-41],
        [5.2755e-39, 3.0093e-33, 7.0974e+22]])


In [4]:
x=torch.rand(5,3)
print(x)

tensor([[0.2547, 0.3313, 0.5070],
        [0.5154, 0.4199, 0.8547],
        [0.3705, 0.9285, 0.3762],
        [0.4865, 0.6147, 0.0039],
        [0.7805, 0.4453, 0.2331]])


In [5]:
x=torch.rand(7,5,3)
print(x)

tensor([[[0.0137, 0.6060, 0.2445],
         [0.3623, 0.8137, 0.1521],
         [0.0211, 0.3043, 0.0347],
         [0.0321, 0.2381, 0.3080],
         [0.8547, 0.9731, 0.5241]],

        [[0.7892, 0.6661, 0.0501],
         [0.4974, 0.5924, 0.8550],
         [0.5811, 0.2214, 0.4009],
         [0.1301, 0.4499, 0.4107],
         [0.2762, 0.1400, 0.5293]],

        [[0.6011, 0.9289, 0.7039],
         [0.9898, 0.5319, 0.4641],
         [0.5767, 0.8291, 0.0613],
         [0.3259, 0.9343, 0.5746],
         [0.4348, 0.6210, 0.9027]],

        [[0.8248, 0.1497, 0.9184],
         [0.5271, 0.9199, 0.7867],
         [0.9294, 0.5368, 0.6380],
         [0.9455, 0.0458, 0.1136],
         [0.8311, 0.8635, 0.4038]],

        [[0.0903, 0.8953, 0.3213],
         [0.0081, 0.3424, 0.7519],
         [0.9362, 0.2274, 0.4255],
         [0.4322, 0.1448, 0.6413],
         [0.1065, 0.4656, 0.9376]],

        [[0.0622, 0.5922, 0.2563],
         [0.0338, 0.1699, 0.6176],
         [0.0652, 0.9435, 0.7072],
         [

Contruct a matrix filled zeros and of dtype long:

In [6]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Contruct a tensor directly from data:

In [7]:
x=torch.tensor([5,5, 3])
print(x)

tensor([5, 5, 3])


or create a tensor based on an existing tensor.These methods will reuse properties of the input tensor e.g. dtype,unless new values are provided by user

In [8]:
x=x.new_ones(5,3,dtype=torch.double) #new_method take in size
print(x)


x2=torch.randn_like(x,dtype=torch.double)#override dtype!
print(x2)                                #result has same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6347,  0.0240,  0.3001],
        [-0.7095, -0.8123,  1.3716],
        [ 1.2181,  2.2821,  0.2323],
        [ 0.2283,  1.0023, -0.1198],
        [ 0.1007,  0.8112, -0.0174]], dtype=torch.float64)


get its size

In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
x.shape

torch.Size([5, 3])

In [11]:
#Addition 1

y =torch.rand(5,3)

print(x+y)

tensor([[1.8396, 1.3844, 1.4645],
        [1.5221, 1.1592, 1.8018],
        [1.3300, 1.5403, 1.2127],
        [1.9631, 1.1871, 1.7326],
        [1.7366, 1.9243, 1.4847]], dtype=torch.float64)


In [12]:
#Addition 2

print(torch.add(x,y))

tensor([[1.8396, 1.3844, 1.4645],
        [1.5221, 1.1592, 1.8018],
        [1.3300, 1.5403, 1.2127],
        [1.9631, 1.1871, 1.7326],
        [1.7366, 1.9243, 1.4847]], dtype=torch.float64)


In [13]:
result =torch.empty(5,3)

torch.add(x,y, out=result)


print(result)

tensor([[1.8396, 1.3844, 1.4645],
        [1.5221, 1.1592, 1.8018],
        [1.3300, 1.5403, 1.2127],
        [1.9631, 1.1871, 1.7326],
        [1.7366, 1.9243, 1.4847]])


In [14]:
 #adds x to y

 y.add_(x)
 print(y)

tensor([[1.8396, 1.3844, 1.4645],
        [1.5221, 1.1592, 1.8018],
        [1.3300, 1.5403, 1.2127],
        [1.9631, 1.1871, 1.7326],
        [1.7366, 1.9243, 1.4847]])


You can use standard NumPy-like indexing with all bells and whistles

In [15]:
print(x[:,1])

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [16]:
x = torch.randn(4,4)
y= x.view(16)
z= x.view(-1,8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.5687])
1.5686596632003784


NumPy Bridge

In [18]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


COverting NumPy array to torch tensor

In [21]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)

np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CUDA tensors

(Language to talk with the GPU)


```
Tensor can be moved onto any device using the .tp method
```

active GPU from Change runtime


In [22]:
torch.cuda.is_available()

True

In [23]:
device  = torch.device("cuda")

In [24]:
device

device(type='cuda')

In [25]:
y= torch.ones_like(x, device=device)


In [26]:
y

tensor([1.], device='cuda:0')

In [27]:
x=torch.ones_like(x)

In [29]:
x_gpu= x.to(device)

In [31]:
# del(x_gpu)